### ISSUE TITLE
ImportError: cannot import name views

### ISSUE THREAD

**Issue by chandlercord** [johnmuth81/cloud-compare#4]
On a fresh clone, I receive this error.

[ccord:/tmp/cloud-compare] master ± python manage.py makemigrations pricing
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Library/Python/2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Library/Python/2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Library/Python/2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.**dict**[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in **get**
    res = instance.**dict**[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/private/tmp/cloud-compare/cloud_compare/urls.py", line 19, in <module>
    from . import views
ImportError: cannot import name views

**Comment by johnmuth81** [comment]
Hmm. Looks like it's time for CI testing.

In any case, I pushed a fix for the issue. Try it now.

**Comment by perrohunter** [comment]
How was this resolved?
