### ISSUE TITLE
aws_populate fails on fresh pull

### ISSUE THREAD

**Issue by johnmuth81** [johnmuth81/cloud-compare#5]
Did a pull to a fresh tree. Failed in aws_populate:

Johns-MBP:cc-fresh johnmuth$ python manage.py aws_populate
AmazonVPC
AmazonSES
AmazonEC2
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(_args, *_options)
  File "/Users/johnmuth/cc-fresh/pricing/management/commands/aws_populate.py", line 91, in handle
    product_family = psku["productFamily"],
KeyError: 'productFamily'
Johns-MBP:cc-fresh johnmuth$

**Comment by johnmuth81** [comment]
Recent AWS price lists have bogus entries. 

Fixed in re-write of scrape/ingest procedures.
